name: Release

on:
  push:
    branches:
      - master
jobs:
  publish-gpr:
    name: Publish to GPR
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v1
        with:
          node-version: 20
      - name: Bump versions and publish packages
        run: |
          npm install
          npx lerna exec npm install
          npx lerna exec npx ncc build
          git add *dist/* --force
          git commit -m 'chore: Update dist'
          npx lerna version --conventional-commits --create-release github --yes
        env:
          GH_TOKEN: ${{ secrets.SEMANTIC_PAT }}