name: Release

on:
  push:
    branches:
      - master
jobs:
  publish-gpr:
    name: Publish Actions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v1
        with:
          node-version: 20
      - name: Bump versions and publish packages
        run: |
          npm install
          npx lerna exec npm run package
          git config user.name "Lerna Bot"
          git config user.email "LernaBot@24g.com"
          git add packages/*/dist/ --force
          git commit -m "chore: Update dist" || echo "No changes to commit"
          npx lerna version --conventional-commits --create-release github --yes
        env:
          GH_TOKEN: ${{ secrets.SEMANTIC_PAT }}